trigger:
  branches:
    include:
      - main
      - master

pool:
  name: AzureVMPool   # your self-hosted VM agent pool

steps:
# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
  displayName: 'Install .NET SDK'

# Restore NuGet packages
- script: dotnet restore OnlineCourseManagement/OnlineCourseManagement.csproj
  displayName: 'Restore NuGet packages'

# Build Web API
- script: dotnet build OnlineCourseManagement/OnlineCourseManagement.csproj -c Release
  displayName: 'Build Web API'

# Publish Web API
- script: dotnet publish OnlineCourseManagement/OnlineCourseManagement.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Web API'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'OCM-Connection'
    appName: 'OCM-API'
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy Web API to App Service'
